apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: webapp-volumes
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ nfs_dir }}
    server: {{ nfs_ip }}
