--- 
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nfs-pv
  namespace: webapp-volumes
spec: 
  accessModes: 
    - ReadWriteMany
  capacity: 
    storage: 10Gi
  mountOptions: 
    - hard
    - nfsvers=4.1
  nfs: 
    path: /srv/nfs
    server: "10.0.1.10"
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  volumeMode: Filesystem
