apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: quay.io/rhte_2019/webapp:v1
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80 
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        volumeMounts:
        - name: site-pvc
          mountPath: /var/www/public
      volumes:
      - name: site-pvc
        persistentVolumeClaim:
          claimName: webapp-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: webapp-service
    namespace: webapp
spec:
    selector:
      app: webapp
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: webapp
  labels:
    app: webapp
  annotations:
      haproxy.org/path-rewrite: "/"
spec:
  rules:
  - host: foo-volumes.bar
    http:
      paths:
      - path: /volumes
        pathType: "Prefix"
        backend:
          service:
            name: webapp-service
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
  namespace: webapp
data:
  servers-increment: "42"
  ssl-redirect: "OFF"
