---
# Workaround to prevent the error: ModuleNotFoundError: No module named 'kubernetes'
- name: Install kubernetes for Python 3 specifically, using the 'pip3' executable
  pip:
    name: kubernetes
    executable: pip3
  become: yes

# $ kubectl create namespace webapp-volumes
- name: Create a k8s namespace
  command: sudo kubectl create namespace webapp
  become: yes
  become_user: kubeadmin

# $ kubectl apply -f webapp-pv.yaml 
- name: Create PV webapp-pv
  command: sudo kubectl apply -f https://raw.githubusercontent.com/saradelrio131/unircp2/main/ansible/manifests/webapp-pv.yaml
  become: yes
  become_user: kubeadmin

# $ kubectl apply -f webapp-pvc.yaml
- name: Create PVC webapp-pvc
  command: sudo kubectl apply -f https://raw.githubusercontent.com/saradelrio131/unircp2/main/ansible/manifests/webapp-pvc.yaml
  become: yes
  become_user: kubeadmin

# $ kubectl apply -f webapp.yaml
- name: Create Deployment, Service, Ingress and ConfigMap
  command: sudo kubectl apply -f https://raw.githubusercontent.com/saradelrio131/unircp2/main/ansible/manifests/webapp.yaml
  become: yes
  become_user: kubeadmin

# Create index.php
- name: copy file /srv/nfs/index.php
  copy:
    src: index.php
    dest: /srv/nfs/index.php
    owner: root
    group: root
    mode: 0644
  become: true
