---
# Workaround to prevent the error: ModuleNotFoundError: No module named 'kubernetes'
- name: Install kubernetes for Python 3 specifically, using the 'pip3' executable
  pip:
    name: kubernetes
    executable: pip3
  become: yes

# $ kubectl create namespace webapp-volumes
#- name: Create a k8s namespace
#  command: sudo kubectl create namespace webapp-volumes
#  become: yes
#  become_user: kubeadmin

# $ kubectl apply -f nfs-pv.yaml 
- name: Create PV nfs-pv
  command: sudo kubectl apply -f https://raw.githubusercontent.com/saradelrio131/unircp2/main/ansible/manifests/pv.yaml
  become: yes
  become_user: kubeadmin
