# Configure firewall
# firewall-cmd --zone=public --permanent --add-port={10250,30000-32767}/tcp
- name: Add port 10250
  command: firewall-cmd --zone=public --permanent --add-port=10250/tcp
  become: true

- name: Add ports 30000-32767
  command: firewall-cmd --zone=public --permanent --add-port=30000-32767/tcp
  become: true

# firewall-cmd --reload
- name: Reload firewall-cmd
  command: firewall-cmd --reload
  become: true

# Join the cluster
- name: Join the cluster
  command: kubeadm join "{{ masterip }}":"{{ masterport }}" --token "{{ token }}" --discovery-token-ca-cert-hash sha256:"{{ hash }}"
  become: true
