# Apply /etc/sysctl.d/k8s.conf
- name: Apply /etc/sysctl.d/k8s.conf
  command: sysctl --system
  become: true

# SWAP
- name: Disable SWAP since kubernetes can't work with swap enabled
  shell: |
    swapoff -a
  become: true

# sed -i '/swap/d' /etc/fstab
- name: Remove swap from fstab
  shell: sed -i '/swap/d' /etc/fstab
  become: true

# Install CRI-O engine
# Configure CRI-O repos
- name: Download repo
  get_url:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo
    dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo
  become: true

- name: Download repo    
  get_url:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
    dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
  become: true
