---
- name: 03-playbook
  hosts: all
  vars_files:
   - "group_vars/install.yaml"
   - "group_vars/configure.yaml"
  gather_facts: false
  roles:
   - configure-dns
   #- configure-firewalld
