# Apply /etc/sysctl.d/k8s.conf
- name: Apply /etc/sysctl.d/k8s.conf
  command: sysctl --system
  become: true

# SWAP
- name: Disable SWAP since kubernetes can't work with swap enabled
  shell: |
    swapoff -a
  become: true

# sed -i '/swap/d' /etc/fstab
- name: Remove swap from fstab
  shell: sed -i '/swap/d' /etc/fstab
  become: true


